title: Python Tutorial
description: Book info
theme: just-the-docs
color_scheme: dark

# Налаштування навігації
nav_external_links:
  - title: GitHub
    url: https://github.com/UkraineCoder/UkraineCoder.github.io
    hide_icon: false

# Налаштування пошуку
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10