title: Python Tutorial
description: Book info
remote_theme: just-the-docs/just-the-docs

# Налаштування навігації
nav_external_links:
  - title: GitHub
    url: https://github.com/UkraineCoder/UkraineCoder.github.io
    hide_icon: false

# Налаштування пошуку
search_enabled: true
search:
  heading_level: 2
  previews: 3